apiVersion: apps/v1
kind: Deployment
metadata:
  name: application
spec:
  replicas: 2
  template:
    spec:
      containers:
      - name: application
        env:
          - name: DATABASE_URL_DEFAULT
            valueFrom:
              secretKeyRef:
                name: postgres
                key: POSTGRES_URL
          - name: DATABASE_URL
            value: $(DATABASE_URL_DEFAULT)?pgbouncer=true&connect_timeout=10&pool_timeout=0

          - name: THUMBOR_URL
            value: https://thumbor.michigantechcourses.com
          - name: THUMBOR_SECURITY_KEY
            valueFrom:
              secretKeyRef:
                name: thumbor
                key: THUMBOR_SECURITY_KEY
          - name: AUTH_TOKEN
            valueFrom:
              secretKeyRef:
                name: application
                key: AUTH_TOKEN
          - name: ENDPOINT
            valueFrom:
              secretKeyRef:
                name: application
                key: ENDPOINT

          - name: DD_AGENT_HOST
            valueFrom:
              fieldRef:
                fieldPath: status.hostIP
        resources:
          requests:
            cpu: 50m
            memory: 256Mi
          limits:
            cpu: 256m
            memory: 1Gi

      initContainers:
        - name: migrate-application-database
          env:
          - name: DATABASE_URL
            valueFrom:
              secretKeyRef:
                name: postgres
                key: DIRECT_TO_POSTGRES_URL
