apiVersion: apps/v1
kind: Deployment
metadata:
  name: application
spec:
  template:
    spec:
      containers:
      - name: application
        env:
          - name: DATABASE_URL
            valueFrom:
              secretKeyRef:
                name: postgres
                key: POSTGRES_URL
      initContainers:
        - name: migrate-application-database
          env:
          - name: DATABASE_URL
            valueFrom:
              secretKeyRef:
                name: postgres
                key: POSTGRES_URL
