apiVersion: apps/v1
kind: Deployment
metadata:
  name: application
spec:
  replicas: 1
  template:
    spec:
      containers:
      - name: application
        env:
          - name: DIRECT_TO_POSTGRES_URL
            valueFrom:
              secretKeyRef:
                name: postgres
                key: DIRECT_TO_POSTGRES_URL
          - name: DATABASE_URL
            value: $(DIRECT_TO_POSTGRES_URL)?connection_limit=50

          - name: THUMBOR_URL
            value: https://thumbor.michigantechcourses.com
          - name: THUMBOR_SECURITY_KEY
            valueFrom:
              secretKeyRef:
                name: thumbor
                key: THUMBOR_SECURITY_KEY
          - name: AUTH_TOKEN
            valueFrom:
              secretKeyRef:
                name: application
                key: AUTH_TOKEN
          - name: DD_AGENT_HOST
            valueFrom:
              fieldRef:
                fieldPath: status.hostIP
        resources:
          requests:
            cpu: "0.2"
            memory: 512Mi
          limits:
            cpu: "1"
            memory: 1.5Gi

      initContainers:
        - name: migrate-application-database
          env:
          - name: DATABASE_URL
            valueFrom:
              secretKeyRef:
                name: postgres
                key: DIRECT_TO_POSTGRES_URL
