apiVersion: apps/v1
kind: Deployment
metadata:
  name: application
spec:
  replicas: 4
  template:
    spec:
      containers:
      - name: application
        env:
          - name: DATABASE_URL
            valueFrom:
              secretKeyRef:
                name: postgres
                key: POSTGRES_URL
          - name: THUMBOR_URL
            value: https://thumbor.michigantechcourses.com
          - name: THUMBOR_SECURITY_KEY
            valueFrom:
              secretKeyRef:
                name: thumbor
                key: THUMBOR_SECURITY_KEY
          - name: AUTH_TOKEN
            valueFrom:
              secretKeyRef:
                name: application
                key: AUTH_TOKEN
          - name: DD_AGENT_HOST
            valueFrom:
              fieldRef:
                fieldPath: status.hostIP
      initContainers:
        - name: migrate-application-database
          env:
          - name: DATABASE_URL
            valueFrom:
              secretKeyRef:
                name: postgres
                key: POSTGRES_URL
