apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: backup-db
spec:
  schedule: "*/5 * * * *"
  failedJobsHistoryLimit: 1
  successfulJobsHistoryLimit: 3
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: db-backup-maker
            image: registry.michigantechcourses.com/db-backup:latest
            env:
            - name: POSTGRES_DB
              valueFrom:
                secretKeyRef:
                  name: postgres
                  key: POSTGRES_DB
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: postgres
                  key: POSTGRES_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres
                  key: POSTGRES_PASSWORD
            - name: POSTGRES_HOST
              value: "postgres"
            - name: AWS_ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                  name: postgres
                  key: AWS_ACCESS_KEY_ID
            - name: AWS_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: postgres
                  key: AWS_SECRET_ACCESS_KEY
            - name: AWS_DEFAULT_REGION
              valueFrom:
                secretKeyRef:
                  name: postgres
                  key: AWS_DEFAULT_REGION
            - name: AWS_ENDPOINT
              valueFrom:
                secretKeyRef:
                  name: postgres
                  key: AWS_ENDPOINT
            - name: S3_BACKUP_PATH
              valueFrom:
                secretKeyRef:
                  name: postgres
                  key: S3_BACKUP_PATH
          restartPolicy: OnFailure
          imagePullSecrets:
          - name: regcred
