apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
spec:
  template:
    metadata:
      annotations:
        ad.datadoghq.com/redis.check_names: '["postgres"]'
        ad.datadoghq.com/redis.init_configs: '[{"host":"%%host%%", "port":5432,"username":"datadog","password":"%%env_POSTGRES_PASSWORD%%"}]'
    spec:
      containers:
        - name: postgres
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: postgredb
          args: ["postgres", "-c", "max_connections=200"]
          env:
          - name: POSTGRES_DB
            valueFrom:
              secretKeyRef:
                name: postgres
                key: POSTGRES_DB
          - name: POSTGRES_USER
            valueFrom:
              secretKeyRef:
                name: postgres
                key: POSTGRES_USER
          - name: POSTGRES_PASSWORD
            valueFrom:
              secretKeyRef:
                name: postgres
                key: POSTGRES_PASSWORD
      volumes:
        - name: postgredb
          persistentVolumeClaim:
            claimName: postgres-pv-claim
