app = "courses-api"

[deploy]
  release_command = "yarn migrations:run"
  kill_timeout = 300

[env]
  THUMBOR_URL = "https://courses-thumbor.fly.dev"
  ENDPOINT = "https://api.michigantechcourses.com"
  NODE_ENV = "production"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 2
  [http_service.concurrency]
    type = "requests"
    soft_limit = 200
    hard_limit = 250

[[http_service.checks]]
  grace_period = "10s"
  method = "get"
  path = "/health"
  protocol = "http"
