apiVersion: v1
kind: Service
metadata:
  name: application
spec:
  ports:
  - port: 80
    targetPort: 3000
  selector:
    app: application
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: application
spec:
  replicas: 2
  selector:
    matchLabels:
      app: application
  template:
    metadata:
      labels:
        app: application
    spec:
      containers:
      - name: application
        image: registry.michigantechcourses.com/backend:latest
        ports:
        - containerPort: 3000
        env:
          - name: REDIS_HOST
            value: "redis"
          - name: REDIS_PORT
            value: "6379"
      initContainers:
        - name: migrate-application-database
          image: registry.michigantechcourses.com/backend:latest
          args: ["migrations:run"]
      imagePullSecrets:
      - name: regcred
