apiVersion: v1
kind: Service
metadata:
  name: postgres
spec:
  ports:
  - port: 5432
    targetPort: 6432
    name: postgres
  - port: 3432
    targetPort: 5432
    name: postgres-direct
  selector:
    app: postgres
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
spec:
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - name: postgres
          image: postgres:13.2
          ports:
            - containerPort: 5432
        - name: pgbouncer
          image: edoburu/pgbouncer@sha256:e173802088fdbd6626a2e9ca66d01c4be029ca04710cca73ae818efa1f4d7dd7
          ports:
            - containerPort: 6432
          env:
          - name: MAX_CLIENT_CONN
            value: "200"
          - name: DEFAULT_POOL_SIZE
            value: "20"
          - name: LISTEN_PORT
            value: "6432"
          - name: POOL_MODE
            value: "transaction"
          livenessProbe:
            tcpSocket:
              port: 6432
            periodSeconds: 60
          lifecycle:
            preStop:
              exec:
                # Allow existing queries clients to complete within 120 seconds
                command: ["/bin/sh", "-c", "killall -INT pgbouncer && sleep 120"]
