name: Deploy to Fly.io
on:
  push:
    branches: ["main"]

jobs:
  deploy:
    name: Deploy to Fly.io
    runs-on: ubuntu-20.04
    concurrency: fly-deploy
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Fly CLI
        uses: superfly/flyctl-actions/setup-flyctl@master

      - name: Deploy to Fly
        run: |
          flyctl deploy -c fly/api.toml --strategy bluegreen
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
