name: Deploy

on: push

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - name: Set context
        uses: azure/k8s-set-context@v1
        with:
          method: kubeconfig
          kubeconfig: ${{ secrets.KUBECONFIG }}

      - name: Wait on lint
        uses: lewagon/wait-on-check-action@v0.2
        with:
          ref: ${{ github.sha }}
          check-name: lint
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          wait-interval: 10

      - name: Wait on tests
        uses: lewagon/wait-on-check-action@v0.2
        with:
          ref: ${{ github.sha }}
          check-name: test
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          wait-interval: 10

      - name: Wait on image
        uses: lewagon/wait-on-check-action@v0.2
        with:
          ref: ${{ github.sha }}
          check-name: build-image
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          wait-interval: 10

      - name: Don't allow concurrent deploys
        uses: softprops/turnstyle@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Add Postgres values
        uses: SpicyPizza/create-envfile@v1
        with:
          envkey_POSTGRES_DB: ${{ secrets.POSTGRES_DB }}
          envkey_POSTGRES_USER: ${{ secrets.POSTGRES_USER }}
          envkey_POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
          envkey_POSTGRES_URL: ${{ secrets.POSTGRES_URL }}
          directory: "infrastructure/overlays/prod/values"
          file_name: "postgres.env"
      
      - name: Add Thumbor values
        uses: SpicyPizza/create-envfile@v1
        with:
          envkey_SECURITY_KEY: ${{ secrets.THUMBOR_SECURITY_KEY }}
          directory: "infrastructure/overlays/prod/values"
          file_name: "thumbor.env"

      - name: Kustomize
        run: kustomize build infrastructure/overlays/prod > kustomized.yaml

      - name: Deploy
        uses: Azure/k8s-deploy@v1.3
        with:
          namespace: 'backend'
          manifests: |
              kustomized.yaml
          images: 'registry.michigantechcourses.com/backend:${{ github.sha }}'
          imagepullsecrets: |
            regcred
          kubectl-version: 'latest'
